//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bot_brainsly_one.src.settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class bot : global::System.Configuration.ApplicationSettingsBase {
        
        private static bot defaultInstance = ((bot)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new bot())));
        
        public static bot Default {
            get {
                return defaultInstance;
            }
        }
    }
}
